### ISSUE TITLE
add new options to download data from Illumina base space via CLI

### ISSUE THREAD

**Issue by m-jahn** [m-jahn/TnSeq-pipe#3]
- apparently `bs-cp` is outdated, update with new tool

**Comment by julienmortier** [comment]
This issue can be fixed by using the BaseSpace Sequence Hub CLI (https://developer.basespace.illumina.com/docs/content/documentation/cli/cli-overview). 
fastq.gz files can be downloaded per biosample using: 
$ bs download biosample -i 568408389 -o ./Documents
more info can be found here: https://developer.basespace.illumina.com/docs/content/documentation/cli/cli-examples
